08:53:29 | Request starting HTTP/1.1 GET http://localhost:27945/api/values  
-------------------------------------------------------------------------------------------------------------------------
08:53:29 | Request finished in 257.977ms 404 
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request starting HTTP/1.1 GET http://localhost:27945/swagger  
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request finished in 1.581ms 301 
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/index.html  
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request finished in 33.181ms 200 text/html
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/swagger-ui.css  
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/swagger-ui-bundle.js  
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/swagger-ui-standalone-preset.js  
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
-------------------------------------------------------------------------------------------------------------------------
08:53:45 | Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
-------------------------------------------------------------------------------------------------------------------------
08:53:46 | Request finished in 358.102ms 200 application/javascript
-------------------------------------------------------------------------------------------------------------------------
08:53:46 | Request finished in 564.156ms 200 text/css
-------------------------------------------------------------------------------------------------------------------------
08:53:46 | Request finished in 672.573ms 200 application/javascript
-------------------------------------------------------------------------------------------------------------------------
08:53:46 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/v1/swagger.json  
-------------------------------------------------------------------------------------------------------------------------
08:53:46 | Request finished in 182.061ms 200 application/json;charset=utf-8
-------------------------------------------------------------------------------------------------------------------------
08:56:06 | Request starting HTTP/1.1 POST http://localhost:27945/api/Authorize/Auth/Email application/json-patch+json 55
-------------------------------------------------------------------------------------------------------------------------
08:56:06 | Executing action method CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) with arguments (CiklumTest.Models.Identyty.LoginRequest) - ModelState is Valid
-------------------------------------------------------------------------------------------------------------------------
08:56:06 | Entity Framework Core 2.1.1-rtm-30846 initialized 'CiklumDbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=___Shared_Database___ 
-------------------------------------------------------------------------------------------------------------------------
08:56:07 | Executed action CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) in 1307.174ms
-------------------------------------------------------------------------------------------------------------------------
08:56:08 | Request finished in 1577.849ms 401 application/json
-------------------------------------------------------------------------------------------------------------------------
08:56:46 | Request starting HTTP/1.1 POST http://localhost:27945/api/Authorize/Auth/Email application/json-patch+json 55
-------------------------------------------------------------------------------------------------------------------------
08:56:46 | Executing action method CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) with arguments (CiklumTest.Models.Identyty.LoginRequest) - ModelState is Valid
-------------------------------------------------------------------------------------------------------------------------
08:57:05 | Entity Framework Core 2.1.1-rtm-30846 initialized 'CiklumDbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=___Shared_Database___ 
-------------------------------------------------------------------------------------------------------------------------
08:58:04 | Request starting HTTP/1.1 GET http://localhost:27945/api/values  
-------------------------------------------------------------------------------------------------------------------------
08:58:04 | Request finished in 216.733ms 404 
-------------------------------------------------------------------------------------------------------------------------
08:58:11 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/index.html  
-------------------------------------------------------------------------------------------------------------------------
08:58:11 | Request finished in 30.925ms 200 text/html
-------------------------------------------------------------------------------------------------------------------------
08:58:12 | Request starting HTTP/1.1 GET http://localhost:27945/swagger/v1/swagger.json  
-------------------------------------------------------------------------------------------------------------------------
08:58:12 | Request finished in 177.172ms 200 application/json;charset=utf-8
-------------------------------------------------------------------------------------------------------------------------
08:58:35 | Request starting HTTP/1.1 POST http://localhost:27945/api/Authorize/Auth/Email application/json-patch+json 55
-------------------------------------------------------------------------------------------------------------------------
08:58:36 | Executing action method CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) with arguments (CiklumTest.Models.Identyty.LoginRequest) - ModelState is Valid
-------------------------------------------------------------------------------------------------------------------------
08:58:39 | Entity Framework Core 2.1.1-rtm-30846 initialized 'CiklumDbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=___Shared_Database___ 
-------------------------------------------------------------------------------------------------------------------------
08:58:52 | Executed action CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) in 16731.883ms
-------------------------------------------------------------------------------------------------------------------------
08:58:53 | POST | /api/Authorize/Auth/Email | Object reference not set to an instance of an object.
   at CiklumTest.Services.LoginService.<GetIdentity>d__7.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Services/ILoginService.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CiklumTest.Controllers.AuthorizeController.<Email>d__3.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Controllers/AuthorizeController.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CiklumTest.Middleware.ErrorHandlingMiddleware.<Invoke>d__4.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Middleware/ErrorHandlingMiddleware.cs:line 37
-------------------------------------------------------------------------------------------------------------------------
08:58:53 | Request finished in 17173.123ms 500 application/json
-------------------------------------------------------------------------------------------------------------------------
08:59:13 | Request starting HTTP/1.1 POST http://localhost:27945/api/Authorize/Auth/Email application/json-patch+json 55
-------------------------------------------------------------------------------------------------------------------------
08:59:13 | Executing action method CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) with arguments (CiklumTest.Models.Identyty.LoginRequest) - ModelState is Valid
-------------------------------------------------------------------------------------------------------------------------
08:59:16 | Entity Framework Core 2.1.1-rtm-30846 initialized 'CiklumDbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=___Shared_Database___ 
-------------------------------------------------------------------------------------------------------------------------
08:59:29 | Executed action CiklumTest.Controllers.AuthorizeController.Email (CiklumTest) in 16214.495ms
-------------------------------------------------------------------------------------------------------------------------
08:59:29 | POST | /api/Authorize/Auth/Email | Object reference not set to an instance of an object.
   at CiklumTest.Services.LoginService.<GetIdentity>d__7.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Services/ILoginService.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CiklumTest.Controllers.AuthorizeController.<Email>d__3.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Controllers/AuthorizeController.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CiklumTest.Middleware.ErrorHandlingMiddleware.<Invoke>d__4.MoveNext() in /Users/user/Projects/CiklumTest/CiklumTest/Middleware/ErrorHandlingMiddleware.cs:line 37
-------------------------------------------------------------------------------------------------------------------------
08:59:29 | Request finished in 16444.119ms 500 application/json
-------------------------------------------------------------------------------------------------------------------------
